name: Legacy Farm
favicon: null
layout_spectrum: 0.18406706023961306
typography_spectrum: 0.5071830477099866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5985376080498099
  lightness: 0.0070197079330682755
  saturation: 0.425865248311311
  rhythmicContrast: 0.6968561627436429
purpose: []
